<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>de.mkoehler.starwars</groupId>
  <artifactId>starwars-parent</artifactId>
  <version>1.0.0</version>
  <packaging>pom</packaging>

  <name>StarWars</name>
  <description>A libGDX project.</description>

  <modules>
    <module>core</module>
    <module>lwjgl3</module>
  </modules>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.release>25</maven.compiler.release>
    <appName>StarWars</appName>
    <gdxVersion>1.14.2</gdxVersion>
    <ashleyVersion>1.7.4</ashleyVersion>
    <!-- Forces LWJGL3 to this version, to avoid warnings on Java 25 and up. -->
    <lwjgl3Version>3.4.3</lwjgl3Version>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.lwjgl</groupId>
        <artifactId>lwjgl</artifactId>
        <version>${lwjgl3Version}</version>
      </dependency>
      <dependency>
        <groupId>org.lwjgl</groupId>
        <artifactId>lwjgl</artifactId>
        <version>${lwjgl3Version}</version>
        <classifier>natives-linux</classifier>
      </dependency>
      <dependency>
        <groupId>org.lwjgl</groupId>
        <artifactId>lwjgl</artifactId>
        <version>${lwjgl3Version}</version>
        <classifier>natives-linux-arm32</classifier>
      </dependency>
      <dependency>
        <groupId>org.lwjgl</groupId>
        <artifactId>lwjgl</artifactId>
        <version>${lwjgl3Version}</version>
        <classifier>natives-linux-arm64</classifier>
      </dependency>
      <dependency>
        <groupId>org.lwjgl</groupId>
        <artifactId>lwjgl</artifactId>
        <version>${lwjgl3Version}</version>
        <classifier>natives-macos</classifier>
      </dependency>
      <dependency>
        <groupId>org.lwjgl</groupId>
        <artifactId>lwjgl</artifactId>
        <version>${lwjgl3Version}</version>
        <classifier>natives-macos-arm64</classifier>
      </dependency>
      <dependency>
        <groupId>org.lwjgl</groupId>
        <artifactId>lwjgl</artifactId>
        <version>${lwjgl3Version}</version>
        <classifier>natives-windows</classifier>
      </dependency>
      <dependency>
        <groupId>org.lwjgl</groupId>
        <artifactId>lwjgl</artifactId>
        <version>${lwjgl3Version}</version>
        <classifier>natives-windows-x86</classifier>
      </dependency>
      <dependency>
        <groupId>org.lwjgl</groupId>
        <artifactId>lwjgl-glfw</artifactId>
        <version>${lwjgl3Version}</version>
      </dependency>
      <dependency>
        <groupId>org.lwjgl</groupId>
        <artifactId>lwjgl-glfw</artifactId>
        <version>${lwjgl3Version}</version>
        <classifier>natives-linux</classifier>
      </dependency>
      <dependency>
        <groupId>org.lwjgl</groupId>
        <artifactId>lwjgl-glfw</artifactId>
        <version>${lwjgl3Version}</version>
        <classifier>natives-linux-arm32</classifier>
      </dependency>
      <dependency>
        <groupId>org.lwjgl</groupId>
        <artifactId>lwjgl-glfw</artifactId>
        <version>${lwjgl3Version}</version>
        <classifier>natives-linux-arm64</classifier>
      </dependency>
      <dependency>
        <groupId>org.lwjgl</groupId>
        <artifactId>lwjgl-glfw</artifactId>
        <version>${lwjgl3Version}</version>
        <classifier>natives-macos</classifier>
      </dependency>
      <dependency>
        <groupId>org.lwjgl</groupId>
        <artifactId>lwjgl-glfw</artifactId>
        <version>${lwjgl3Version}</version>
        <classifier>natives-macos-arm64</classifier>
      </dependency>
      <dependency>
        <groupId>org.lwjgl</groupId>
        <artifactId>lwjgl-glfw</artifactId>
        <version>${lwjgl3Version}</version>
        <classifier>natives-windows</classifier>
      </dependency>
      <dependency>
        <groupId>org.lwjgl</groupId>
        <artifactId>lwjgl-glfw</artifactId>
        <version>${lwjgl3Version}</version>
        <classifier>natives-windows-x86</classifier>
      </dependency>
      <dependency>
        <groupId>org.lwjgl</groupId>
        <artifactId>lwjgl-jemalloc</artifactId>
        <version>${lwjgl3Version}</version>
      </dependency>
      <dependency>
        <groupId>org.lwjgl</groupId>
        <artifactId>lwjgl-jemalloc</artifactId>
        <version>${lwjgl3Version}</version>
        <classifier>natives-linux</classifier>
      </dependency>
      <dependency>
        <groupId>org.lwjgl</groupId>
        <artifactId>lwjgl-jemalloc</artifactId>
        <version>${lwjgl3Version}</version>
        <classifier>natives-linux-arm32</classifier>
      </dependency>
      <dependency>
        <groupId>org.lwjgl</groupId>
        <artifactId>lwjgl-jemalloc</artifactId>
        <version>${lwjgl3Version}</version>
        <classifier>natives-linux-arm64</classifier>
      </dependency>
      <dependency>
        <groupId>org.lwjgl</groupId>
        <artifactId>lwjgl-jemalloc</artifactId>
        <version>${lwjgl3Version}</version>
        <classifier>natives-macos</classifier>
      </dependency>
      <dependency>
        <groupId>org.lwjgl</groupId>
        <artifactId>lwjgl-jemalloc</artifactId>
        <version>${lwjgl3Version}</version>
        <classifier>natives-macos-arm64</classifier>
      </dependency>
      <dependency>
        <groupId>org.lwjgl</groupId>
        <artifactId>lwjgl-jemalloc</artifactId>
        <version>${lwjgl3Version}</version>
        <classifier>natives-windows</classifier>
      </dependency>
      <dependency>
        <groupId>org.lwjgl</groupId>
        <artifactId>lwjgl-jemalloc</artifactId>
        <version>${lwjgl3Version}</version>
        <classifier>natives-windows-x86</classifier>
      </dependency>
      <dependency>
        <groupId>org.lwjgl</groupId>
        <artifactId>lwjgl-openal</artifactId>
        <version>${lwjgl3Version}</version>
      </dependency>
      <dependency>
        <groupId>org.lwjgl</groupId>
        <artifactId>lwjgl-openal</artifactId>
        <version>${lwjgl3Version}</version>
        <classifier>natives-linux</classifier>
      </dependency>
      <dependency>
        <groupId>org.lwjgl</groupId>
        <artifactId>lwjgl-openal</artifactId>
        <version>${lwjgl3Version}</version>
        <classifier>natives-linux-arm32</classifier>
      </dependency>
      <dependency>
        <groupId>org.lwjgl</groupId>
        <artifactId>lwjgl-openal</artifactId>
        <version>${lwjgl3Version}</version>
        <classifier>natives-linux-arm64</classifier>
      </dependency>
      <dependency>
        <groupId>org.lwjgl</groupId>
        <artifactId>lwjgl-openal</artifactId>
        <version>${lwjgl3Version}</version>
        <classifier>natives-macos</classifier>
      </dependency>
      <dependency>
        <groupId>org.lwjgl</groupId>
        <artifactId>lwjgl-openal</artifactId>
        <version>${lwjgl3Version}</version>
        <classifier>natives-macos-arm64</classifier>
      </dependency>
      <dependency>
        <groupId>org.lwjgl</groupId>
        <artifactId>lwjgl-openal</artifactId>
        <version>${lwjgl3Version}</version>
        <classifier>natives-windows</classifier>
      </dependency>
      <dependency>
        <groupId>org.lwjgl</groupId>
        <artifactId>lwjgl-openal</artifactId>
        <version>${lwjgl3Version}</version>
        <classifier>natives-windows-x86</classifier>
      </dependency>
      <dependency>
        <groupId>org.lwjgl</groupId>
        <artifactId>lwjgl-opengl</artifactId>
        <version>${lwjgl3Version}</version>
      </dependency>
      <dependency>
        <groupId>org.lwjgl</groupId>
        <artifactId>lwjgl-opengl</artifactId>
        <version>${lwjgl3Version}</version>
        <classifier>natives-linux</classifier>
      </dependency>
      <dependency>
        <groupId>org.lwjgl</groupId>
        <artifactId>lwjgl-opengl</artifactId>
        <version>${lwjgl3Version}</version>
        <classifier>natives-linux-arm32</classifier>
      </dependency>
      <dependency>
        <groupId>org.lwjgl</groupId>
        <artifactId>lwjgl-opengl</artifactId>
        <version>${lwjgl3Version}</version>
        <classifier>natives-linux-arm64</classifier>
      </dependency>
      <dependency>
        <groupId>org.lwjgl</groupId>
        <artifactId>lwjgl-opengl</artifactId>
        <version>${lwjgl3Version}</version>
        <classifier>natives-macos</classifier>
      </dependency>
      <dependency>
        <groupId>org.lwjgl</groupId>
        <artifactId>lwjgl-opengl</artifactId>
        <version>${lwjgl3Version}</version>
        <classifier>natives-macos-arm64</classifier>
      </dependency>
      <dependency>
        <groupId>org.lwjgl</groupId>
        <artifactId>lwjgl-opengl</artifactId>
        <version>${lwjgl3Version}</version>
        <classifier>natives-windows</classifier>
      </dependency>
      <dependency>
        <groupId>org.lwjgl</groupId>
        <artifactId>lwjgl-opengl</artifactId>
        <version>${lwjgl3Version}</version>
        <classifier>natives-windows-x86</classifier>
      </dependency>
      <dependency>
        <groupId>org.lwjgl</groupId>
        <artifactId>lwjgl-stb</artifactId>
        <version>${lwjgl3Version}</version>
      </dependency>
      <dependency>
        <groupId>org.lwjgl</groupId>
        <artifactId>lwjgl-stb</artifactId>
        <version>${lwjgl3Version}</version>
        <classifier>natives-linux</classifier>
      </dependency>
      <dependency>
        <groupId>org.lwjgl</groupId>
        <artifactId>lwjgl-stb</artifactId>
        <version>${lwjgl3Version}</version>
        <classifier>natives-linux-arm32</classifier>
      </dependency>
      <dependency>
        <groupId>org.lwjgl</groupId>
        <artifactId>lwjgl-stb</artifactId>
        <version>${lwjgl3Version}</version>
        <classifier>natives-linux-arm64</classifier>
      </dependency>
      <dependency>
        <groupId>org.lwjgl</groupId>
        <artifactId>lwjgl-stb</artifactId>
        <version>${lwjgl3Version}</version>
        <classifier>natives-macos</classifier>
      </dependency>
      <dependency>
        <groupId>org.lwjgl</groupId>
        <artifactId>lwjgl-stb</artifactId>
        <version>${lwjgl3Version}</version>
        <classifier>natives-macos-arm64</classifier>
      </dependency>
      <dependency>
        <groupId>org.lwjgl</groupId>
        <artifactId>lwjgl-stb</artifactId>
        <version>${lwjgl3Version}</version>
        <classifier>natives-windows</classifier>
      </dependency>
      <dependency>
        <groupId>org.lwjgl</groupId>
        <artifactId>lwjgl-stb</artifactId>
        <version>${lwjgl3Version}</version>
        <classifier>natives-windows-x86</classifier>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.13.0</version>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>
</project>
